create table shibui.templates (
      id bigint generated by default as identity not null,
      name character varying not null,
      secret character varying null,
      constraint template_pkey primary key (id)
) TABLESPACE pg_default;